// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package db

import (
	"context"
	"encoding/json"
	"time"
)

const createAuditEvent = `-- name: CreateAuditEvent :one

INSERT INTO audit_events (item_id, actor_id, action, payload)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at
`

type CreateAuditEventParams struct {
	ItemID  int64           `json:"item_id"`
	ActorID int64           `json:"actor_id"`
	Action  string          `json:"action"`
	Payload json.RawMessage `json:"payload"`
}

type CreateAuditEventRow struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

// queries/audit.sql
func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (CreateAuditEventRow, error) {
	row := q.db.QueryRowContext(ctx, createAuditEvent,
		arg.ItemID,
		arg.ActorID,
		arg.Action,
		arg.Payload,
	)
	var i CreateAuditEventRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listAuditEventsByItem = `-- name: ListAuditEventsByItem :many
SELECT
    ae.id,
    ae.item_id,
    ae.actor_id,
    u.full_name  AS actor_full_name,
    u.email      AS actor_email,
    u.role       AS actor_role,
    ae.action,
    ae.payload,
    ae.tx_hash,
    ae.created_at
FROM audit_events ae
JOIN users u ON u.id = ae.actor_id
WHERE ae.item_id = $1
ORDER BY ae.created_at ASC
`

type ListAuditEventsByItemRow struct {
	ID            int64           `json:"id"`
	ItemID        int64           `json:"item_id"`
	ActorID       int64           `json:"actor_id"`
	ActorFullName string          `json:"actor_full_name"`
	ActorEmail    string          `json:"actor_email"`
	ActorRole     string          `json:"actor_role"`
	Action        string          `json:"action"`
	Payload       json.RawMessage `json:"payload"`
	TxHash        string          `json:"tx_hash"`
	CreatedAt     time.Time       `json:"created_at"`
}

func (q *Queries) ListAuditEventsByItem(ctx context.Context, itemID int64) ([]ListAuditEventsByItemRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEventsByItem, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditEventsByItemRow{}
	for rows.Next() {
		var i ListAuditEventsByItemRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.ActorID,
			&i.ActorFullName,
			&i.ActorEmail,
			&i.ActorRole,
			&i.Action,
			&i.Payload,
			&i.TxHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAuditEventTxHash = `-- name: UpdateAuditEventTxHash :exec
UPDATE audit_events
SET tx_hash = $1
WHERE id = $2
`

type UpdateAuditEventTxHashParams struct {
	TxHash string `json:"tx_hash"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateAuditEventTxHash(ctx context.Context, arg UpdateAuditEventTxHashParams) error {
	_, err := q.db.ExecContext(ctx, updateAuditEventTxHash, arg.TxHash, arg.ID)
	return err
}
