// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: disposal_documents.sql

package db

import (
	"context"
	"time"
)

const countDisposalDocumentsByItemID = `-- name: CountDisposalDocumentsByItemID :one
SELECT COUNT(*) FROM disposal_documents
WHERE item_id = $1
`

func (q *Queries) CountDisposalDocumentsByItemID(ctx context.Context, itemID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDisposalDocumentsByItemID, itemID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDisposalDocument = `-- name: CreateDisposalDocument :one

INSERT INTO disposal_documents (
    item_id, filename, url, uploaded_by
)
VALUES ($1, $2, $3, $4)
RETURNING id, uploaded_at
`

type CreateDisposalDocumentParams struct {
	ItemID     int64  `json:"item_id"`
	Filename   string `json:"filename"`
	Url        string `json:"url"`
	UploadedBy int64  `json:"uploaded_by"`
}

type CreateDisposalDocumentRow struct {
	ID         int64     `json:"id"`
	UploadedAt time.Time `json:"uploaded_at"`
}

// queries/disposal_documents.sql
// Disposal document queries.
func (q *Queries) CreateDisposalDocument(ctx context.Context, arg CreateDisposalDocumentParams) (CreateDisposalDocumentRow, error) {
	row := q.db.QueryRowContext(ctx, createDisposalDocument,
		arg.ItemID,
		arg.Filename,
		arg.Url,
		arg.UploadedBy,
	)
	var i CreateDisposalDocumentRow
	err := row.Scan(&i.ID, &i.UploadedAt)
	return i, err
}

const deleteDisposalDocument = `-- name: DeleteDisposalDocument :exec
DELETE FROM disposal_documents
WHERE id = $1 AND item_id = $2
`

type DeleteDisposalDocumentParams struct {
	ID     int64 `json:"id"`
	ItemID int64 `json:"item_id"`
}

func (q *Queries) DeleteDisposalDocument(ctx context.Context, arg DeleteDisposalDocumentParams) error {
	_, err := q.db.ExecContext(ctx, deleteDisposalDocument, arg.ID, arg.ItemID)
	return err
}

const getDisposalDocumentByID = `-- name: GetDisposalDocumentByID :one
SELECT id, item_id, filename, url, uploaded_at, uploaded_by FROM disposal_documents
WHERE id = $1
`

func (q *Queries) GetDisposalDocumentByID(ctx context.Context, id int64) (DisposalDocument, error) {
	row := q.db.QueryRowContext(ctx, getDisposalDocumentByID, id)
	var i DisposalDocument
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Filename,
		&i.Url,
		&i.UploadedAt,
		&i.UploadedBy,
	)
	return i, err
}

const listDisposalDocumentsByItemID = `-- name: ListDisposalDocumentsByItemID :many
SELECT id, item_id, filename, url, uploaded_at, uploaded_by FROM disposal_documents
WHERE item_id = $1
ORDER BY uploaded_at ASC
`

func (q *Queries) ListDisposalDocumentsByItemID(ctx context.Context, itemID int64) ([]DisposalDocument, error) {
	rows, err := q.db.QueryContext(ctx, listDisposalDocumentsByItemID, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DisposalDocument{}
	for rows.Next() {
		var i DisposalDocument
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.Filename,
			&i.Url,
			&i.UploadedAt,
			&i.UploadedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
