// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const barcodeExists = `-- name: BarcodeExists :one
SELECT EXISTS(
    SELECT 1 FROM items WHERE barcode = $1
) AS exists
`

func (q *Queries) BarcodeExists(ctx context.Context, barcode string) (bool, error) {
	row := q.db.QueryRowContext(ctx, barcodeExists, barcode)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createItem = `-- name: CreateItem :one
INSERT INTO items (
    barcode, inventory_number, name, category_id, room_id,
    description, status,
    created_by, last_edited_by
)
VALUES ($1, $2, $3, $4, $5, $6, 'active', $7, $7)
RETURNING id, created_at, updated_at
`

type CreateItemParams struct {
	Barcode         string `json:"barcode"`
	InventoryNumber string `json:"inventory_number"`
	Name            string `json:"name"`
	CategoryID      int64  `json:"category_id"`
	RoomID          int64  `json:"room_id"`
	Description     string `json:"description"`
	CreatedBy       int64  `json:"created_by"`
}

type CreateItemRow struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (CreateItemRow, error) {
	row := q.db.QueryRowContext(ctx, createItem,
		arg.Barcode,
		arg.InventoryNumber,
		arg.Name,
		arg.CategoryID,
		arg.RoomID,
		arg.Description,
		arg.CreatedBy,
	)
	var i CreateItemRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const getItemByBarcode = `-- name: GetItemByBarcode :one
SELECT id, barcode, inventory_number, name, category_id, category_name, room_id, room_name, building_id, building_name, building_address, description, status, tx_hash, created_at, updated_at, pending_disposal_at, disposed_at, created_by, creator_full_name, creator_email, creator_role, creator_created_at, creator_updated_at, last_edited_by, editor_full_name, editor_email, editor_role, editor_created_at, editor_updated_at FROM item_details
WHERE barcode = $1
`

func (q *Queries) GetItemByBarcode(ctx context.Context, barcode string) (ItemDetail, error) {
	row := q.db.QueryRowContext(ctx, getItemByBarcode, barcode)
	var i ItemDetail
	err := row.Scan(
		&i.ID,
		&i.Barcode,
		&i.InventoryNumber,
		&i.Name,
		&i.CategoryID,
		&i.CategoryName,
		&i.RoomID,
		&i.RoomName,
		&i.BuildingID,
		&i.BuildingName,
		&i.BuildingAddress,
		&i.Description,
		&i.Status,
		&i.TxHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PendingDisposalAt,
		&i.DisposedAt,
		&i.CreatedBy,
		&i.CreatorFullName,
		&i.CreatorEmail,
		&i.CreatorRole,
		&i.CreatorCreatedAt,
		&i.CreatorUpdatedAt,
		&i.LastEditedBy,
		&i.EditorFullName,
		&i.EditorEmail,
		&i.EditorRole,
		&i.EditorCreatedAt,
		&i.EditorUpdatedAt,
	)
	return i, err
}

const getItemByID = `-- name: GetItemByID :one

SELECT id, barcode, inventory_number, name, category_id, category_name, room_id, room_name, building_id, building_name, building_address, description, status, tx_hash, created_at, updated_at, pending_disposal_at, disposed_at, created_by, creator_full_name, creator_email, creator_role, creator_created_at, creator_updated_at, last_edited_by, editor_full_name, editor_email, editor_role, editor_created_at, editor_updated_at FROM item_details
WHERE id = $1
`

// queries/items.sql
// Item queries — all SELECTs go through the item_details view.
// The view owns the JOIN logic; queries here stay intentionally simple.
func (q *Queries) GetItemByID(ctx context.Context, id int64) (ItemDetail, error) {
	row := q.db.QueryRowContext(ctx, getItemByID, id)
	var i ItemDetail
	err := row.Scan(
		&i.ID,
		&i.Barcode,
		&i.InventoryNumber,
		&i.Name,
		&i.CategoryID,
		&i.CategoryName,
		&i.RoomID,
		&i.RoomName,
		&i.BuildingID,
		&i.BuildingName,
		&i.BuildingAddress,
		&i.Description,
		&i.Status,
		&i.TxHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PendingDisposalAt,
		&i.DisposedAt,
		&i.CreatedBy,
		&i.CreatorFullName,
		&i.CreatorEmail,
		&i.CreatorRole,
		&i.CreatorCreatedAt,
		&i.CreatorUpdatedAt,
		&i.LastEditedBy,
		&i.EditorFullName,
		&i.EditorEmail,
		&i.EditorRole,
		&i.EditorCreatedAt,
		&i.EditorUpdatedAt,
	)
	return i, err
}

const inventoryNumberExists = `-- name: InventoryNumberExists :one
SELECT EXISTS(
    SELECT 1 FROM items WHERE inventory_number = $1
) AS exists
`

func (q *Queries) InventoryNumberExists(ctx context.Context, inventoryNumber string) (bool, error) {
	row := q.db.QueryRowContext(ctx, inventoryNumberExists, inventoryNumber)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listItems = `-- name: ListItems :many
SELECT id, barcode, inventory_number, name, category_id, category_name, room_id, room_name, building_id, building_name, building_address, description, status, tx_hash, created_at, updated_at, pending_disposal_at, disposed_at, created_by, creator_full_name, creator_email, creator_role, creator_created_at, creator_updated_at, last_edited_by, editor_full_name, editor_email, editor_role, editor_created_at, editor_updated_at FROM item_details
WHERE
    ($1::bigint IS NULL OR category_id = $1) AND
    ($2::bigint     IS NULL OR room_id     = $2)     AND
    ($3::text        IS NULL OR status      = $3)      AND
    ($4::timestamptz IS NULL OR created_at >= $4) AND
    ($5::timestamptz   IS NULL OR created_at <= $5)
ORDER BY created_at DESC
`

type ListItemsParams struct {
	CategoryID sql.NullInt64  `json:"category_id"`
	RoomID     sql.NullInt64  `json:"room_id"`
	Status     sql.NullString `json:"status"`
	DateFrom   sql.NullTime   `json:"date_from"`
	DateTo     sql.NullTime   `json:"date_to"`
}

func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]ItemDetail, error) {
	rows, err := q.db.QueryContext(ctx, listItems,
		arg.CategoryID,
		arg.RoomID,
		arg.Status,
		arg.DateFrom,
		arg.DateTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemDetail{}
	for rows.Next() {
		var i ItemDetail
		if err := rows.Scan(
			&i.ID,
			&i.Barcode,
			&i.InventoryNumber,
			&i.Name,
			&i.CategoryID,
			&i.CategoryName,
			&i.RoomID,
			&i.RoomName,
			&i.BuildingID,
			&i.BuildingName,
			&i.BuildingAddress,
			&i.Description,
			&i.Status,
			&i.TxHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PendingDisposalAt,
			&i.DisposedAt,
			&i.CreatedBy,
			&i.CreatorFullName,
			&i.CreatorEmail,
			&i.CreatorRole,
			&i.CreatorCreatedAt,
			&i.CreatorUpdatedAt,
			&i.LastEditedBy,
			&i.EditorFullName,
			&i.EditorEmail,
			&i.EditorRole,
			&i.EditorCreatedAt,
			&i.EditorUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveItemToRoom = `-- name: MoveItemToRoom :exec
UPDATE items
SET
    room_id        = $1,
    last_edited_by = $2,
    updated_at     = NOW()
WHERE id = $3
`

type MoveItemToRoomParams struct {
	RoomID       int64 `json:"room_id"`
	LastEditedBy int64 `json:"last_edited_by"`
	ID           int64 `json:"id"`
}

func (q *Queries) MoveItemToRoom(ctx context.Context, arg MoveItemToRoomParams) error {
	_, err := q.db.ExecContext(ctx, moveItemToRoom, arg.RoomID, arg.LastEditedBy, arg.ID)
	return err
}

const updateItem = `-- name: UpdateItem :exec
UPDATE items
SET
    description    = $1,
    last_edited_by = $2,
    updated_at     = NOW()
WHERE id = $3
`

type UpdateItemParams struct {
	Description  string `json:"description"`
	LastEditedBy int64  `json:"last_edited_by"`
	ID           int64  `json:"id"`
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) error {
	_, err := q.db.ExecContext(ctx, updateItem, arg.Description, arg.LastEditedBy, arg.ID)
	return err
}

const updateItemStatus = `-- name: UpdateItemStatus :exec
UPDATE items
SET
    status         = $1,
    last_edited_by = $2,
    updated_at     = NOW()
WHERE id = $3
`

type UpdateItemStatusParams struct {
	Status       string `json:"status"`
	LastEditedBy int64  `json:"last_edited_by"`
	ID           int64  `json:"id"`
}

func (q *Queries) UpdateItemStatus(ctx context.Context, arg UpdateItemStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateItemStatus, arg.Status, arg.LastEditedBy, arg.ID)
	return err
}

const updateItemTxHash = `-- name: UpdateItemTxHash :exec
UPDATE items
SET tx_hash = $1
WHERE id = $2
`

type UpdateItemTxHashParams struct {
	TxHash string `json:"tx_hash"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateItemTxHash(ctx context.Context, arg UpdateItemTxHashParams) error {
	_, err := q.db.ExecContext(ctx, updateItemTxHash, arg.TxHash, arg.ID)
	return err
}
