// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lookup.sql

package db

import (
	"context"
)

const countItemsByCategory = `-- name: CountItemsByCategory :one
SELECT COUNT(*) FROM items WHERE category_id = $1
`

func (q *Queries) CountItemsByCategory(ctx context.Context, categoryID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countItemsByCategory, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countItemsByRoom = `-- name: CountItemsByRoom :one
SELECT COUNT(*) FROM items WHERE room_id = $1
`

func (q *Queries) CountItemsByRoom(ctx context.Context, roomID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countItemsByRoom, roomID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRoomsByBuilding = `-- name: CountRoomsByBuilding :one
SELECT COUNT(*) FROM rooms WHERE building_id = $1
`

func (q *Queries) CountRoomsByBuilding(ctx context.Context, buildingID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRoomsByBuilding, buildingID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBuilding = `-- name: CreateBuilding :one

INSERT INTO buildings (name, address) VALUES ($1, $2) RETURNING id
`

type CreateBuildingParams struct {
	Name    string `json:"name"`
	Address string `json:"address"`
}

// ── Buildings ─────────────────────────────────────────────────────────────────
func (q *Queries) CreateBuilding(ctx context.Context, arg CreateBuildingParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createBuilding, arg.Name, arg.Address)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createCategory = `-- name: CreateCategory :one


INSERT INTO categories (name) VALUES ($1) RETURNING id
`

// queries/lookup.sql
// Reference data queries: categories, buildings, rooms.
// ── Categories ───────────────────────────────────────────────────────────────
func (q *Queries) CreateCategory(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, createCategory, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createRoom = `-- name: CreateRoom :one

INSERT INTO rooms (name, building_id) VALUES ($1, $2) RETURNING id
`

type CreateRoomParams struct {
	Name       string `json:"name"`
	BuildingID int64  `json:"building_id"`
}

// ── Rooms ─────────────────────────────────────────────────────────────────────
func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createRoom, arg.Name, arg.BuildingID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteBuilding = `-- name: DeleteBuilding :exec
DELETE FROM buildings WHERE id = $1
`

func (q *Queries) DeleteBuilding(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBuilding, id)
	return err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM rooms WHERE id = $1
`

func (q *Queries) DeleteRoom(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRoom, id)
	return err
}

const getBuildingByID = `-- name: GetBuildingByID :one
SELECT id, name, address FROM buildings WHERE id = $1
`

func (q *Queries) GetBuildingByID(ctx context.Context, id int64) (Building, error) {
	row := q.db.QueryRowContext(ctx, getBuildingByID, id)
	var i Building
	err := row.Scan(&i.ID, &i.Name, &i.Address)
	return i, err
}

const getBuildingByName = `-- name: GetBuildingByName :one
SELECT id, name, address FROM buildings WHERE name = $1
`

func (q *Queries) GetBuildingByName(ctx context.Context, name string) (Building, error) {
	row := q.db.QueryRowContext(ctx, getBuildingByName, name)
	var i Building
	err := row.Scan(&i.ID, &i.Name, &i.Address)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, name FROM categories WHERE id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getCategoryByName = `-- name: GetCategoryByName :one
SELECT id, name FROM categories WHERE name = $1
`

func (q *Queries) GetCategoryByName(ctx context.Context, name string) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByName, name)
	var i Category
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT r.id, r.name, r.building_id, b.name AS building_name, b.address AS building_address
FROM rooms r
JOIN buildings b ON b.id = r.building_id
WHERE r.id = $1
`

type GetRoomByIDRow struct {
	ID              int64  `json:"id"`
	Name            string `json:"name"`
	BuildingID      int64  `json:"building_id"`
	BuildingName    string `json:"building_name"`
	BuildingAddress string `json:"building_address"`
}

func (q *Queries) GetRoomByID(ctx context.Context, id int64) (GetRoomByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getRoomByID, id)
	var i GetRoomByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BuildingID,
		&i.BuildingName,
		&i.BuildingAddress,
	)
	return i, err
}

const getRoomByNameAndBuilding = `-- name: GetRoomByNameAndBuilding :one
SELECT r.id, r.name, r.building_id, b.name AS building_name, b.address AS building_address
FROM rooms r
JOIN buildings b ON b.id = r.building_id
WHERE r.name = $1 AND r.building_id = $2
`

type GetRoomByNameAndBuildingParams struct {
	Name       string `json:"name"`
	BuildingID int64  `json:"building_id"`
}

type GetRoomByNameAndBuildingRow struct {
	ID              int64  `json:"id"`
	Name            string `json:"name"`
	BuildingID      int64  `json:"building_id"`
	BuildingName    string `json:"building_name"`
	BuildingAddress string `json:"building_address"`
}

func (q *Queries) GetRoomByNameAndBuilding(ctx context.Context, arg GetRoomByNameAndBuildingParams) (GetRoomByNameAndBuildingRow, error) {
	row := q.db.QueryRowContext(ctx, getRoomByNameAndBuilding, arg.Name, arg.BuildingID)
	var i GetRoomByNameAndBuildingRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BuildingID,
		&i.BuildingName,
		&i.BuildingAddress,
	)
	return i, err
}

const listBuildings = `-- name: ListBuildings :many
SELECT id, name, address FROM buildings ORDER BY name ASC
`

func (q *Queries) ListBuildings(ctx context.Context) ([]Building, error) {
	rows, err := q.db.QueryContext(ctx, listBuildings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Building{}
	for rows.Next() {
		var i Building
		if err := rows.Scan(&i.ID, &i.Name, &i.Address); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, name FROM categories ORDER BY name ASC
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRooms = `-- name: ListRooms :many
SELECT r.id, r.name, r.building_id, b.name AS building_name, b.address AS building_address
FROM rooms r
JOIN buildings b ON b.id = r.building_id
ORDER BY b.name ASC, r.name ASC
`

type ListRoomsRow struct {
	ID              int64  `json:"id"`
	Name            string `json:"name"`
	BuildingID      int64  `json:"building_id"`
	BuildingName    string `json:"building_name"`
	BuildingAddress string `json:"building_address"`
}

func (q *Queries) ListRooms(ctx context.Context) ([]ListRoomsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoomsRow{}
	for rows.Next() {
		var i ListRoomsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BuildingID,
			&i.BuildingName,
			&i.BuildingAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomsByBuilding = `-- name: ListRoomsByBuilding :many
SELECT r.id, r.name, r.building_id, b.name AS building_name, b.address AS building_address
FROM rooms r
JOIN buildings b ON b.id = r.building_id
WHERE r.building_id = $1
ORDER BY r.name ASC
`

type ListRoomsByBuildingRow struct {
	ID              int64  `json:"id"`
	Name            string `json:"name"`
	BuildingID      int64  `json:"building_id"`
	BuildingName    string `json:"building_name"`
	BuildingAddress string `json:"building_address"`
}

func (q *Queries) ListRoomsByBuilding(ctx context.Context, buildingID int64) ([]ListRoomsByBuildingRow, error) {
	rows, err := q.db.QueryContext(ctx, listRoomsByBuilding, buildingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoomsByBuildingRow{}
	for rows.Next() {
		var i ListRoomsByBuildingRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BuildingID,
			&i.BuildingName,
			&i.BuildingAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBuilding = `-- name: UpdateBuilding :exec
UPDATE buildings SET name = $1, address = $2 WHERE id = $3
`

type UpdateBuildingParams struct {
	Name    string `json:"name"`
	Address string `json:"address"`
	ID      int64  `json:"id"`
}

func (q *Queries) UpdateBuilding(ctx context.Context, arg UpdateBuildingParams) error {
	_, err := q.db.ExecContext(ctx, updateBuilding, arg.Name, arg.Address, arg.ID)
	return err
}

const updateCategory = `-- name: UpdateCategory :exec
UPDATE categories SET name = $1 WHERE id = $2
`

type UpdateCategoryParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateCategory, arg.Name, arg.ID)
	return err
}

const updateRoom = `-- name: UpdateRoom :exec
UPDATE rooms SET name = $1, building_id = $2 WHERE id = $3
`

type UpdateRoomParams struct {
	Name       string `json:"name"`
	BuildingID int64  `json:"building_id"`
	ID         int64  `json:"id"`
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) error {
	_, err := q.db.ExecContext(ctx, updateRoom, arg.Name, arg.BuildingID, arg.ID)
	return err
}
