// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Building struct {
	ID      int64  `json:"id"`
	Name    string `json:"name"`
	Address string `json:"address"`
}

type Category struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Item struct {
	ID           int64     `json:"id"`
	Barcode      string    `json:"barcode"`
	Name         string    `json:"name"`
	CategoryID   int64     `json:"category_id"`
	RoomID       int64     `json:"room_id"`
	Description  string    `json:"description"`
	PhotoUrl     string    `json:"photo_url"`
	Status       string    `json:"status"`
	TxHash       string    `json:"tx_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	CreatedBy    int64     `json:"created_by"`
	LastEditedBy int64     `json:"last_edited_by"`
}

type ItemDetail struct {
	ID               int64     `json:"id"`
	Barcode          string    `json:"barcode"`
	Name             string    `json:"name"`
	CategoryID       int64     `json:"category_id"`
	CategoryName     string    `json:"category_name"`
	RoomID           int64     `json:"room_id"`
	RoomName         string    `json:"room_name"`
	BuildingID       int64     `json:"building_id"`
	BuildingName     string    `json:"building_name"`
	BuildingAddress  string    `json:"building_address"`
	Description      string    `json:"description"`
	PhotoUrl         string    `json:"photo_url"`
	Status           string    `json:"status"`
	TxHash           string    `json:"tx_hash"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
	CreatedBy        int64     `json:"created_by"`
	CreatorFullName  string    `json:"creator_full_name"`
	CreatorEmail     string    `json:"creator_email"`
	CreatorRole      string    `json:"creator_role"`
	CreatorCreatedAt time.Time `json:"creator_created_at"`
	CreatorUpdatedAt time.Time `json:"creator_updated_at"`
	LastEditedBy     int64     `json:"last_edited_by"`
	EditorFullName   string    `json:"editor_full_name"`
	EditorEmail      string    `json:"editor_email"`
	EditorRole       string    `json:"editor_role"`
	EditorCreatedAt  time.Time `json:"editor_created_at"`
	EditorUpdatedAt  time.Time `json:"editor_updated_at"`
}

type Room struct {
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	BuildingID int64  `json:"building_id"`
}

type User struct {
	ID           int64     `json:"id"`
	FullName     string    `json:"full_name"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
