// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: photos.sql

package db

import (
	"context"
)

const addItemPhoto = `-- name: AddItemPhoto :one

INSERT INTO item_photos (item_id, url)
VALUES ($1, $2)
RETURNING id, item_id, url, created_at
`

type AddItemPhotoParams struct {
	ItemID int64  `json:"item_id"`
	Url    string `json:"url"`
}

// queries/photos.sql
func (q *Queries) AddItemPhoto(ctx context.Context, arg AddItemPhotoParams) (ItemPhoto, error) {
	row := q.db.QueryRowContext(ctx, addItemPhoto, arg.ItemID, arg.Url)
	var i ItemPhoto
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Url,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllItemPhotos = `-- name: DeleteAllItemPhotos :exec
DELETE FROM item_photos WHERE item_id = $1
`

func (q *Queries) DeleteAllItemPhotos(ctx context.Context, itemID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAllItemPhotos, itemID)
	return err
}

const deleteItemPhoto = `-- name: DeleteItemPhoto :exec
DELETE FROM item_photos
WHERE id = $1 AND item_id = $2
`

type DeleteItemPhotoParams struct {
	ID     int64 `json:"id"`
	ItemID int64 `json:"item_id"`
}

func (q *Queries) DeleteItemPhoto(ctx context.Context, arg DeleteItemPhotoParams) error {
	_, err := q.db.ExecContext(ctx, deleteItemPhoto, arg.ID, arg.ItemID)
	return err
}

const listItemPhotos = `-- name: ListItemPhotos :many
SELECT id, item_id, url, created_at
FROM item_photos
WHERE item_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListItemPhotos(ctx context.Context, itemID int64) ([]ItemPhoto, error) {
	rows, err := q.db.QueryContext(ctx, listItemPhotos, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemPhoto{}
	for rows.Next() {
		var i ItemPhoto
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.Url,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
