// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: photos.sql

package db

import (
	"context"
)

const addItemPhoto = `-- name: AddItemPhoto :one

INSERT INTO item_photos (item_id, url)
VALUES ($1, $2)
RETURNING id, item_id, url, created_at
`

type AddItemPhotoParams struct {
	ItemID int64  `json:"item_id"`
	Url    string `json:"url"`
}

// queries/photos.sql
func (q *Queries) AddItemPhoto(ctx context.Context, arg AddItemPhotoParams) (ItemPhoto, error) {
	row := q.db.QueryRowContext(ctx, addItemPhoto, arg.ItemID, arg.Url)
	var i ItemPhoto
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Url,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllItemPhotos = `-- name: DeleteAllItemPhotos :exec
DELETE FROM item_photos WHERE item_id = $1
`

func (q *Queries) DeleteAllItemPhotos(ctx context.Context, itemID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAllItemPhotos, itemID)
	return err
}

const deleteItemPhoto = `-- name: DeleteItemPhoto :exec
DELETE FROM item_photos
WHERE id = $1 AND item_id = $2
`

type DeleteItemPhotoParams struct {
	ID     int64 `json:"id"`
	ItemID int64 `json:"item_id"`
}

func (q *Queries) DeleteItemPhoto(ctx context.Context, arg DeleteItemPhotoParams) error {
	_, err := q.db.ExecContext(ctx, deleteItemPhoto, arg.ID, arg.ItemID)
	return err
}

const deleteItemPhotoData = `-- name: DeleteItemPhotoData :exec
DELETE FROM item_photos_data WHERE photo_id = $1
`

func (q *Queries) DeleteItemPhotoData(ctx context.Context, photoID int64) error {
	_, err := q.db.ExecContext(ctx, deleteItemPhotoData, photoID)
	return err
}

const getItemPhotoData = `-- name: GetItemPhotoData :one
SELECT id, photo_id, data, mime_type, created_at
FROM item_photos_data
WHERE photo_id = $1
`

func (q *Queries) GetItemPhotoData(ctx context.Context, photoID int64) (ItemPhotoData, error) {
	row := q.db.QueryRowContext(ctx, getItemPhotoData, photoID)
	var i ItemPhotoData
	err := row.Scan(
		&i.ID,
		&i.PhotoID,
		&i.Data,
		&i.MimeType,
		&i.CreatedAt,
	)
	return i, err
}

const listItemPhotos = `-- name: ListItemPhotos :many
SELECT id, item_id, url, created_at
FROM item_photos
WHERE item_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListItemPhotos(ctx context.Context, itemID int64) ([]ItemPhoto, error) {
	rows, err := q.db.QueryContext(ctx, listItemPhotos, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemPhoto{}
	for rows.Next() {
		var i ItemPhoto
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.Url,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertItemPhotoData = `-- name: UpsertItemPhotoData :one
INSERT INTO item_photos_data (photo_id, data, mime_type)
VALUES ($1, $2, $3)
ON CONFLICT (photo_id) DO UPDATE
SET data = EXCLUDED.data, mime_type = EXCLUDED.mime_type
RETURNING id, photo_id, data, mime_type, created_at
`

type UpsertItemPhotoDataParams struct {
	PhotoID  int64 `json:"photo_id"`
	Data     []byte `json:"data"`
	MimeType string `json:"mime_type"`
}

func (q *Queries) UpsertItemPhotoData(ctx context.Context, arg UpsertItemPhotoDataParams) (ItemPhotoData, error) {
	row := q.db.QueryRowContext(ctx, upsertItemPhotoData, arg.PhotoID, arg.Data, arg.MimeType)
	var i ItemPhotoData
	err := row.Scan(
		&i.ID,
		&i.PhotoID,
		&i.Data,
		&i.MimeType,
		&i.CreatedAt,
	)
	return i, err
}
