// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"time"
)

type Querier interface {
	BarcodeExists(ctx context.Context, barcode string) (bool, error)
	CountUsersByRole(ctx context.Context, role string) (int64, error)
	// ── Buildings ─────────────────────────────────────────────────────────────────
	CreateBuilding(ctx context.Context, arg CreateBuildingParams) (int64, error)
	// queries/lookup.sql
	// Reference data queries: categories, buildings, rooms.
	// ── Categories ───────────────────────────────────────────────────────────────
	CreateCategory(ctx context.Context, name string) (int64, error)
	CreateItem(ctx context.Context, arg CreateItemParams) (CreateItemRow, error)
	// ── Rooms ─────────────────────────────────────────────────────────────────────
	CreateRoom(ctx context.Context, arg CreateRoomParams) (int64, error)
	// queries/users.sql
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteBuilding(ctx context.Context, id int64) error
	DeleteCategory(ctx context.Context, id int64) error
	DeleteRoom(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	EmailExists(ctx context.Context, email string) (bool, error)
	GetBuildingByID(ctx context.Context, id int64) (Building, error)
	GetCategoryByID(ctx context.Context, id int64) (Category, error)
	GetItemByBarcode(ctx context.Context, barcode string) (ItemDetail, error)
	// queries/items.sql
	// Item queries — all SELECTs go through the item_details view.
	// The view owns the JOIN logic; queries here stay intentionally simple.
	GetItemByID(ctx context.Context, id int64) (ItemDetail, error)
	GetRoomByID(ctx context.Context, id int64) (GetRoomByIDRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	ListBuildings(ctx context.Context) ([]Building, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListItems(ctx context.Context, arg ListItemsParams) ([]ItemDetail, error)
	ListRooms(ctx context.Context) ([]ListRoomsRow, error)
	ListRoomsByBuilding(ctx context.Context, buildingID int64) ([]ListRoomsByBuildingRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateBuilding(ctx context.Context, arg UpdateBuildingParams) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error
	UpdateItem(ctx context.Context, arg UpdateItemParams) error
	UpdateItemStatus(ctx context.Context, arg UpdateItemStatusParams) error
	UpdateItemTxHash(ctx context.Context, arg UpdateItemTxHashParams) error
	UpdateRoom(ctx context.Context, arg UpdateRoomParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (time.Time, error)
}

var _ Querier = (*Queries)(nil)
